### ISSUE TITLE
when I install this plugin, restart the kibana is error

### ISSUE THREAD

**Issue by vs412237401** [Webiks/kibana-API#12]
elasticsearch 5.1.1
kibana 5.1.1
the error message is follow:
======================================
/data/work/elastic/kibana-5.1.1/bin$ ./kibana
  log   [06:00:03.111] [info][status][plugin:kibana@5.1.1] Status changed from uninitialized to green - Ready
  log   [06:00:03.153] [info][status][plugin:elasticsearch@5.1.1] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [06:00:03.178] [fatal] TypeError: server.plugins.elasticsearch.getCluster is not a function
    at exports.default (/data/work/elastic/kibana-5.1.1/plugins/kibana_api/server/routes.js:8:59)
    at ScopedPlugin.init [as externalInit] (/data/work/elastic/kibana-5.1.1/plugins/kibana_api/index.js:32:13)
    at ScopedPlugin.tryCatcher (/data/work/elastic/kibana-5.1.1/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.attempt.Promise.try (/data/work/elastic/kibana-5.1.1/node_modules/bluebird/js/main/method.js:30:24)
    at /data/work/elastic/kibana-5.1.1/src/server/plugins/plugin.js:160:44
    at undefined.next (native)
    at step (/data/work/elastic/kibana-5.1.1/src/server/plugins/plugin.js:11:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
FATAL TypeError: server.plugins.elasticsearch.getCluster is not a function
    at exports.default (/data/work/elastic/kibana-5.1.1/plugins/kibana_api/server/routes.js:8:59)
    at ScopedPlugin.init [as externalInit] (/data/work/elastic/kibana-5.1.1/plugins/kibana_api/index.js:32:13)
    at ScopedPlugin.tryCatcher (/data/work/elastic/kibana-5.1.1/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.attempt.Promise.try (/data/work/elastic/kibana-5.1.1/node_modules/bluebird/js/main/method.js:30:24)
    at /data/work/elastic/kibana-5.1.1/src/server/plugins/plugin.js:160:44
    at undefined.next (native)
    at step (/data/work/elastic/kibana-5.1.1/src/server/plugins/plugin.js:11:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ytzlax** [comment]
Hi,
I will fix the bug in Sunday, I will let you know.

**Comment by ytzlax** [comment]
@vs412237401, I fixed the bug, please download the plugin again
