### ISSUE TITLE
Kibana 6.4 with security 

### ISSUE THREAD

**Issue by gilmau** [Webiks/kibana-API#54]
Hi.
When I turn on the security in kibana 6.4, for some reason, the Kibana-API doesn't work properly.
Do you know why?
Thanks!

**Comment by ytzlax** [comment]
Hi,
I will check it(don't know when)

**Comment by gilmau** [comment]
We've noticed that the **node_modules** folder is missing in all of the Kibana-API plugin 6.4 and upper, so we copy this folder from an older plugin version. 
If the folder is missing, the install fails completely.
When the folder is copying from older version, the install succeed but doesn't work eventually.
Why the **node_modules** is missing שמג is it possible to install the plug without it?

**Comment by ytzlax** [comment]
How did you download the plugin?
By git clone or by download one of the releases?

**Comment by gilmau** [comment]
download one of the releases - kibana-api plugin (v6.4.2_0.6.0)

**Comment by ytzlax** [comment]
Hi, you don't need the node modules to run the plugin

**Comment by ttgile** [comment]
Hi,

When installing the zip file without the data module we get the below error:

./bin/kibana-plugin install "file:///opt/install/kibana-api_6.4.3_0.6.0.zip"
Attempting to transfer from file:///opt/install/kibana-api_6.4.3_0.6.0.zip
Error: ENOTFOUND
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/file:///opt/install/kibana-api_6.4.3_0.6.0.zip/file:///opt/install/kibana-api_6.4.3_0.6.0.zip-6.4.3.zip
Plugin installation was unsuccessful due to error "No valid url specified."
[root@vDevELK kibana]# service kibana stop
kibana stopped.
[root@vDevELK kibana]# pwd
/usr/share/kibana
[root@vDevELK kibana]# ./bin/kibana-plugin install "file:///opt/install/kibana-api_6.4.3.zip"
Attempting to transfer from file:///opt/install/kibana-api_6.4.3.zip
Error: ENOTFOUND
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/file:///opt/install/kibana-api_6.4.3.zip/file:///opt/install/kibana-api_6.4.3.zip-6.4.3.zip
Plugin installation was unsuccessful due to error "No valid url specified."
[root@vDevELK kibana]# ./bin/kibana-plugin install "file:///opt/install/kibana-api_6.4.3.zip"
Attempting to transfer from file:///opt/install/kibana-api_6.4.3.zip
Transferring 629309 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false --uiSettings.enabled=false
(node:30580) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
FATAL { Error: Optimizations failure.
   6478 modules

    ERROR in ./plugins/kibana_api/public/kibana-api-service.js
    Module not found: Error: Can't resolve 'rison' in '/usr/share/kibana/plugins/kibana_api/public'

    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:378:27)
    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:47:26)
    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:241:12)
    at applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:514:14)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:511:11)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:671:19)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:662:11)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
    at /usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:282:11
    at step (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:90:11)
    at done (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:99:22)
    at /usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:105:15
    at _class.boundWorkers (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:76:13)
    at enqueue (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:96:17)
    at /usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:116:11
    at Array.forEach (<anonymous>)
    at _class.runTasks (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:94:13)
    at UglifyJsPlugin.optimizeFn (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:195:16)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.compilation.plugin (/usr/share/kibana/node_modules/webpack/lib/BannerPlugin.js:67:5)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:657:10)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
  cause:
   { Error: Optimizations failure.
   6478 modules

    ERROR in ./plugins/kibana_api/public/kibana-api-service.js
    Module not found: Error: Can't resolve 'rison' in '/usr/share/kibana/plugins/kibana_api/public'

    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:378:27)
    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:47:26)
    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:241:12)
    at applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:514:14)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:511:11)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:671:19)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:662:11)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
    at /usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:282:11
    at step (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:90:11)
    at done (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:99:22)
    at /usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:105:15
    at _class.boundWorkers (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:76:13)
    at enqueue (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:96:17)
    at /usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:116:11
    at Array.forEach (<anonymous>)
    at _class.runTasks (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:94:13)
    at UglifyJsPlugin.optimizeFn (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:195:16)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:204:14)
    at Compilation.compilation.plugin (/usr/share/kibana/node_modules/webpack/lib/BannerPlugin.js:67:5)
    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:657:10)
    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
     data:
      { errors: [Array],
        warnings: [],
        version: '3.6.0',
        hash: '21611548730ca18ca3ab',
        time: 380583,
        publicPath: '__REPLACE_WITH_PUBLIC_PATH__',
        assetsByChunkName: [Object],
        assets: [Array],
        filteredAssets: 0,
        entrypoints: [Object],
        chunks: [Array],
        modules: [Array],
        filteredModules: 0,
        children: [Array] },
     isBoom: true,
     isServer: true,
     output: { statusCode: 500, payload: [Object], headers: {} },
     reformat: [Function],
     typeof: [Function] },
  isOperational: true,
  data:
   { errors:
      [ './plugins/kibana_api/public/kibana-api-service.js\nModule not found: Error: Can\'t resolve \'rison\' in \'/usr/share/kibana/plugins/kibana_api/public\'\nresolve \'rison\' in \'/usr/share/kibana/plugins/kibana_api/public\'\n  Parsed request is a module\n  using description file: /usr/share/kibana/plugins/kibana_api/package.json (relative path: ./public)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /usr/share/kibana/plugins/kibana_api/package.json (relative path: ./public)\n    resolve as module\n      /usr/share/kibana/plugins/kibana_api/public/webpackShims doesn\'t exist or is not a directory\n      /usr/share/kibana/plugins/kibana_api/webpackShims doesn\'t exist or is not a directory\n      /usr/share/kibana/plugins/webpackShims doesn\'t exist or is not a directory\n      /usr/share/webpackShims doesn\'t exist or is not a directory\n      /usr/webpackShims doesn\'t exist or is not a directory\n      /webpackShims doesn\'t exist or is not a directory\n      looking for modules in /usr/share/kibana/webpackShims\n        using description file: /usr/share/kibana/package.json (relative path: ./webpackShims)\n          Field \'browser\' doesn\'t contain a valid alias configuration\n        after using description file: /usr/share/kibana/package.json (relative path: ./webpackShims)\n          using description file: /usr/share/kibana/package.json (relative path: ./webpackShims/rison)\n            no extension\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/rison doesn\'t exist\n            .js\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/rison.js doesn\'t exist\n            .json\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/rison.json doesn\'t exist\n            as directory\n              /usr/share/kibana/webpackShims/rison doesn\'t exist\n      looking for modules in /usr/share/kibana/webpackShims\n        using description file: /usr/share/kibana/package.json (relative path: ./webpackShims)\n          Field \'browser\' doesn\'t contain a valid alias configuration\n        after using description file: /usr/share/kibana/package.json (relative path: ./webpackShims)\n          using description file: /usr/share/kibana/package.json (relative path: ./webpackShims/rison)\n            no extension\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/rison doesn\'t exist\n            .js\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/rison.js doesn\'t exist\n            .json\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/rison.json doesn\'t exist\n            as directory\n              /usr/share/kibana/webpackShims/rison doesn\'t exist\n      /usr/share/kibana/plugins/kibana_api/public/node_modules doesn\'t exist or is not a directory\n      /usr/share/kibana/plugins/kibana_api/node_modules doesn\'t exist or is not a directory\n      /usr/share/kibana/plugins/node_modules doesn\'t exist or is not a directory\n      /usr/share/node_modules doesn\'t exist or is not a directory\n      /usr/node_modules doesn\'t exist or is not a directory\n      /node_modules doesn\'t exist or is not a directory\n      looking for modules in /usr/share/kibana/node_modules\n        using description file: /usr/share/kibana/package.json (relative path: ./node_modules)\n          Field \'browser\' doesn\'t contain a valid alias configuration\n        after using description file: /usr/share/kibana/package.json (relative path: ./node_modules)\n          using description file: /usr/share/kibana/package.json (relative path: ./node_modules/rison)\n            no extension\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/rison doesn\'t exist\n            .js\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/rison.js doesn\'t exist\n            .json\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/rison.json doesn\'t exist\n            as directory\n              /usr/share/kibana/node_modules/rison doesn\'t exist\n      looking for modules in /usr/share/kibana/node_modules\n        using description file: /usr/share/kibana/package.json (relative path: ./node_modules)\n          Field \'browser\' doesn\'t contain a valid alias configuration\n        after using description file: /usr/share/kibana/package.json (relative path: ./node_modules)\n          using description file: /usr/share/kibana/package.json (relative path: ./node_modules/rison)\n            no extension\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/rison doesn\'t exist\n            .js\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/rison.js doesn\'t exist\n            .json\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/rison.json doesn\'t exist\n            as directory\n              /usr/share/kibana/node_modules/rison doesn\'t exist\n[/usr/share/kibana/plugins/kibana_api/public/webpackShims]\n[/usr/share/kibana/plugins/kibana_api/webpackShims]\n[/usr/share/kibana/plugins/webpackShims]\n[/usr/share/webpackShims]\n[/usr/webpackShims]\n[/webpackShims]\n[/usr/share/kibana/webpackShims/rison]\n[/usr/share/kibana/webpackShims/rison.js]\n[/usr/share/kibana/webpackShims/rison.json]\n[/usr/share/kibana/webpackShims/rison]\n[/usr/share/kibana/webpackShims/rison]\n[/usr/share/kibana/webpackShims/rison.js]\n[/usr/share/kibana/webpackShims/rison.json]\n[/usr/share/kibana/webpackShims/rison]\n[/usr/share/kibana/plugins/kibana_api/public/node_modules]\n[/usr/share/kibana/plugins/kibana_api/node_modules]\n[/usr/share/kibana/plugins/node_modules]\n[/usr/share/node_modules]\n[/usr/node_modules]\n[/node_modules]\n[/usr/share/kibana/node_modules/rison]\n[/usr/share/kibana/node_modules/rison.js]\n[/usr/share/kibana/node_modules/rison.json]\n[/usr/share/kibana/node_modules/rison]\n[/usr/share/kibana/node_modules/rison]\n[/usr/share/kibana/node_modules/rison.js]\n[/usr/share/kibana/node_modules/rison.json]\n[/usr/share/kibana/node_modules/rison]\n @ ./plugins/kibana_api/public/kibana-api-service.js 14:13-29\n @ ./plugins/kibana_api/public/hack.js\n @ ./node_modules/val-loader/dist/cjs.js!./src/optimize/create_ui_exports_module.js?{"type":"hacks","modules":["plugins/searchprofiler/register","plugins/ml/hacks/toggle_app_link_in_nav","plugins/timelion/lib/panel_registry","plugins/timelion/panels/timechart/timechart","plugins/xpack_main/hacks/check_xpack_info_change","plugins/xpack_main/hacks/telemetry_opt_in","plugins/xpack_main/hacks/telemetry_trigger","plugins/graph/hacks/toggle_app_link_in_nav","plugins/monitoring/hacks/toggle_app_link_in_nav","plugins/security/hacks/on_session_timeout","plugins/security/hacks/on_unauthorized_response","plugins/grokdebugger/sections/grokdebugger/register","plugins/apm/hacks/toggle_app_link_in_nav","plugins/kibana_api/hack","plugins/console/hacks/register","plugins/kibana/dev_tools/hacks/hide_empty_tools","plugins/reporting/hacks/job_completion_notifier"]}\n @ ./src/ui/public/chrome/chrome.js\n @ ./src/ui/public/chrome/index.js\n @ ./src/core_plugins/state_session_storage_redirect/public/index.js\n @ ./optimize/bundles/stateSessionStorageRedirect.entry.js' ],
     warnings: [],
     version: '3.6.0',
     hash: '21611548730ca18ca3ab',
     time: 380583,
     publicPath: '__REPLACE_WITH_PUBLIC_PATH__',
     assetsByChunkName:
      { commons: [Array],
        kibana: [Array],
        ml: [Array],
        apm: [Array],
        monitoring: [Array],
        timelion: [Array],
        graph: [Array],
        status_page: [Array],
        login: [Array],
        kibana_api: [Array],
        logout: [Array],
        stateSessionStorageRedirect: 'stateSessionStorageRedirect.bundle.js',
        dashboardViewer: 'dashboardViewer.bundle.js',
        vendors: [Array] },
     assets:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     filteredAssets: 0,
     entrypoints:
      { ml: [Object],
        stateSessionStorageRedirect: [Object],
        status_page: [Object],
        timelion: [Object],
        graph: [Object],
        monitoring: [Object],
        login: [Object],
        logout: [Object],
        dashboardViewer: [Object],
        apm: [Object],
        kibana_api: [Object],
        kibana: [Object] },
     chunks:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     modules:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        ... 6378 more items ],
     filteredModules: 0,
     children:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        ... 111 more items ] },
  isBoom: true,
  isServer: true,
  output:
   { statusCode: 500,
     payload:
      { statusCode: 500,
        error: 'Internal Server Error',
        message: 'An internal server error occurred' },
     headers: {} },
  reformat: [Function],
  typeof: [Function] }

{"type":"log","@timestamp":"2019-05-14T17:38:43Z","tags":["warning","config","deprecation"],"pid":30580,"message":"uiSettings.enabled is deprecated and is no longer used"}
{"type":"log","@timestamp":"2019-05-14T17:39:06Z","tags":["info","optimize"],"pid":30580,"message":"Optimizing and caching bundles for ml, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, login, logout, dashboardViewer, apm, kibana_api and kibana. This may take a few minutes"}
{"type":"error","@timestamp":"2019-05-14T17:45:28Z","tags":["fatal"],"pid":30580,"level":"fatal","error":{"message":"Optimizations failure.\n   6478 modules\n    \n    \u001b[1m\u001b[31mERROR in ./plugins/kibana_api/public/kibana-api-service.js\n    Module not found: Error: Can't resolve 'rison' in '/usr/share/kibana/plugins/kibana_api/public'\u001b[39m\u001b[22m\n","name":"Error","stack":"Error: Optimizations failure.\n   6478 modules\n    \n    \u001b[1m\u001b[31mERROR in ./plugins/kibana_api/public/kibana-api-service.js\n    Module not found: Error: Can't resolve 'rison' in '/usr/share/kibana/plugins/kibana_api/public'\u001b[39m\u001b[22m\n\n    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:378:27)\n    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:47:26)\n    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:241:12)\n    at applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:514:14)\n    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)\n    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:78:5)\n    at Compiler.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)\n    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:511:11)\n    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)\n    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:671:19)\n    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)\n    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:662:11)\n    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)\n    at /usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:282:11\n    at step (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:90:11)\n    at done (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:99:22)\n    at /usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:105:15\n    at _class.boundWorkers (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:76:13)\n    at enqueue (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:96:17)\n    at /usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:116:11\n    at Array.forEach (<anonymous>)\n    at _class.runTasks (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:94:13)\n    at UglifyJsPlugin.optimizeFn (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:195:16)\n    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:204:14)\n    at Compilation.compilation.plugin (/usr/share/kibana/node_modules/webpack/lib/BannerPlugin.js:67:5)\n    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)\n    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:657:10)\n    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)"},"message":"Optimizations failure.\n   6478 modules\n    \n    ERROR in ./plugins/kibana_api/public/kibana-api-service.js\n    Module not found: Error: Can't resolve 'rison' in '/usr/share/kibana/plugins/kibana_api/public'\n"}
"
