### ISSUE TITLE
kibana 7.0 support

### ISSUE THREAD

**Issue by chenchuangc** [Webiks/kibana-API#55]
can it support kibana 7.0?

**Comment by edmiester777** [comment]
Tried building and installing for 7.0.1, and it appears that the kibana libraries have changed. 
The code gave the following exception:
```sh
Error: handler method did not return a value, a promise, or throw an error
          at module.exports.internals.Manager.execute (/usr/share/kibana/node_modules/hapi/lib/toolkit.js:52:29)
          at process._tickCallback (internal/process/next_tick.js:68:7)
```
The 7.x support will probably take a little time, but I am working on supporting it. PR will be posted when I make progress.

**Comment by edmiester777** [comment]
I have submitted a PR for an updated version to work with 7.0.x, and I have published a release binary that you can install on my fork. Let me know if there are issues with the port.

**Comment by ych861031** [comment]
I used the updated version submitted by @edmiester777 on 7.0.1, but I got an empty view.


![螢幕快照 2019-08-30 下午1 34 24](https://user-images.githubusercontent.com/32362231/63995397-ea364180-cb2a-11e9-8b5e-ff66fcf37c88.png)


Does anyone know what I miss?
