### ISSUE TITLE
Kibana 6.8.0

### ISSUE THREAD

**Issue by gilmau** [Webiks/kibana-API#57]
Hi
I was trying to install the lastest version of the plugin on Kibana 6.8.0.
This is the error I get the second I login to Kibana (with and without the security enable)
and than the Kibana crushed:

C:\Users\gilm\Desktop\ek 6.8.0\kibana-6.8.0-windows-x86_64\plugins\kibana_api\server\routes.js:27
                reply(obj);
                ^
TypeError: reply is not a function
    at C:/Users/gilm/Desktop/ek 6.8.0/kibana-6.8.0-windows-x86_64/plugins/kibana_api/server/routes.js:34:17
    at C:\Users\gilm\Desktop\ek 6.8.0\kibana-6.8.0-windows-x86_64\plugins\kibana_api\node_modules\jsonfile\index.js:46:5
    at C:\Users\gilm\Desktop\ek 6.8.0\kibana-6.8.0-windows-x86_64\plugins\kibana_api\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

There's something to do about it?
Thanks!

**Comment by ytzlax** [comment]
Hi,
the plugin still don't support 6.8.0 version

**Comment by ytzlax** [comment]
Hi, please consider use kibana REST API

https://www.elastic.co/guide/en/kibana/master/api.html

Does meets your needs?

**Comment by gilmau** [comment]
We are using the Kibana-api to change the refresh time and the time filter to update Kibana I-frame  that is hosted in our web page.
We couldn't find this functionally in the Kibana REST-API documentation 

We consider to upgrade to 6.8.0 because security element is open in the basic license.

**Comment by SterlingSC86** [comment]
Would be great to get 6.7 support as well.
I installed the 7.0 fork. Clearing a filter works, however adding one crashes Kibana.
Any plans to support these versions?

**Comment by ytzlax** [comment]
@SterlingSC86
In which feature do you intend to use in kibana API?

**Comment by SterlingSC86** [comment]
Just the filtering, however I had a look at the code and I don't think it will do what I need.

**Comment by ytzlax** [comment]
I edited the next file, now it's more clear.
https://github.com/Webiks/kibana-API/wiki/Filter-functions#addsearchchip

**Comment by SterlingSC86** [comment]
Thanks for the update. Adding a filter and specifying the field is no longer crashing Kibana the however the filter is still not applying.
